import type { PersonaRoute, Persona } from '@/types/assessment';

// ─── Persona Routing ───
export const PERSONA_ROUTES: PersonaRoute[] = [
  { label: "Sinh viên / Học sinh", persona_id: "mai", emoji: "🎓" },
  { label: "Mới đi làm 1–3 năm", persona_id: "ngoc", emoji: "🌱" },
  { label: "Nhân viên văn phòng / Corporate", persona_id: "minh", emoji: "🧭" },
  { label: "Freelancer / Tự kinh doanh", persona_id: "ha", emoji: "🦋" },
  { label: "Digital Nomad / Creator / YouTuber", persona_id: "khanh", emoji: "🧳" },
  { label: "Quản lý / Chủ doanh nghiệp nhỏ", persona_id: "linh", emoji: "💼" },
  { label: "Phụ nữ / Mẹ cân bằng gia đình & sự nghiệp", persona_id: "van", emoji: "🌸" },
  { label: "Giáo viên / Công chức / Viên chức", persona_id: "thao", emoji: "🌾" },
  { label: "Lãnh đạo cấp cao / Doanh nhân", persona_id: "lan", emoji: "🏔️" },
];

// ─── All Personas ───
export const PERSONAS: Record<string, Persona> = {
  mai: {
    id: "mai",
    label: "Sinh viên / Học sinh",
    emoji: "🎓",
    color: "#1D9E75",
    maxdiff_instruction: "Trong hành trình tìm lại sự cân bằng, điều gì QUAN TRỌNG NHẤT với bạn và điều gì ÍT QUAN TRỌNG NHẤT?",
    most_label: "QUAN TRỌNG NHẤT",
    least_label: "ÍT QUAN TRỌNG NHẤT",
    problem_pool: [
      { id: "mai_p1", label: "Tự tin hơn vào bản thân", description: "Vấn đề liên quan đến tự tin hơn vào bản thân" },
      { id: "mai_p2", label: "Biết mình thực sự muốn gì", description: "Vấn đề liên quan đến biết mình thực sự muốn gì" },
      { id: "mai_p3", label: "Không còn cảm giác lạc lõng", description: "Vấn đề liên quan đến không còn cảm giác lạc lõng" },
      { id: "mai_p4", label: "Học được cách quản lý cảm xúc", description: "Vấn đề liên quan đến học được cách quản lý cảm xúc" },
      { id: "mai_p5", label: "Có định hướng rõ ràng cho tương lai", description: "Vấn đề liên quan đến có định hướng rõ ràng cho tương lai" },
      { id: "mai_p6", label: "Bớt so sánh bản thân với người khác", description: "Vấn đề liên quan đến bớt so sánh bản thân với người khác" },
      { id: "mai_p7", label: "Tìm được cộng đồng cùng chí hướng", description: "Vấn đề liên quan đến tìm được cộng đồng cùng chí hướng" },
      { id: "mai_p8", label: "Cân bằng việc học và cuộc sống", description: "Vấn đề liên quan đến cân bằng việc học và cuộc sống" },
      { id: "mai_p9", label: "Hiểu được điểm mạnh của mình", description: "Vấn đề liên quan đến hiểu được điểm mạnh của mình" },
    ],
    sets: [
      { set_id: "mai_s1", set_label: "Nhóm 1", items: ["mai_p1", "mai_p2", "mai_p3", "mai_p4"] },
      { set_id: "mai_s2", set_label: "Nhóm 2", items: ["mai_p2", "mai_p5", "mai_p6", "mai_p7"] },
      { set_id: "mai_s3", set_label: "Nhóm 3", items: ["mai_p3", "mai_p5", "mai_p8", "mai_p9"] },
      { set_id: "mai_s4", set_label: "Nhóm 4", items: ["mai_p1", "mai_p4", "mai_p6", "mai_p9"] },
      { set_id: "mai_s5", set_label: "Nhóm 5", items: ["mai_p2", "mai_p4", "mai_p8", "mai_p9"] },
      { set_id: "mai_s6", set_label: "Nhóm 6", items: ["mai_p1", "mai_p3", "mai_p6", "mai_p7"] },
      { set_id: "mai_s7", set_label: "Nhóm 7", items: ["mai_p4", "mai_p5", "mai_p7", "mai_p9"] },
      { set_id: "mai_s8", set_label: "Nhóm 8", items: ["mai_p1", "mai_p2", "mai_p5", "mai_p8"] },
      { set_id: "mai_s9", set_label: "Nhóm 9", items: ["mai_p3", "mai_p4", "mai_p7", "mai_p8"] }
    ],
    course_mapping: [
      { triggered_by: ["mai_p1","mai_p2","mai_p9"], problem_theme: "Khủng hoảng bản sắc & tự nhận thức", recommended_course: "EQ Foundations — 21 ngày", course_type: "online", cta: "Bắt đầu miễn phí 7 ngày", urgency_message: "Đây là nền tảng cần xây trước tất cả mọi thứ khác." },
      { triggered_by: ["mai_p3","mai_p6","mai_p7"], problem_theme: "Áp lực xã hội & so sánh", recommended_course: "Cộng đồng Nedu Gen Z", course_type: "community", cta: "Tham gia cộng đồng ngay", urgency_message: "Bạn không cần đi con đường này một mình." },
      { triggered_by: ["mai_p4","mai_p5","mai_p8"], problem_theme: "Kỷ luật bản thân & quản lý cảm xúc", recommended_course: "EQ Foundations — Module Kỷ Luật & Cảm Xúc", course_type: "online", cta: "Xem chi tiết chương trình", urgency_message: "Kỷ luật thật sự bắt đầu từ hiểu cảm xúc, không phải ý chí." },
    ],
  },

  ngoc: {
    id: "ngoc",
    label: "Mới đi làm 1–3 năm",
    emoji: "🌱",
    color: "#639922",
    maxdiff_instruction: "Đối diện với áp lực hằng ngày, điều gì giúp bạn ĐỨNG VỮNG NHẤT và điều gì ÍT GIÚP ÍT NHẤT?",
    most_label: "GIÚP ĐỨNG VỮNG NHẤT",
    least_label: "ÍT GIÚP ÍCH NHẤT",
    problem_pool: [
      { id: "ngoc_p1", label: "Biết cách không mang việc về nhà", description: "Vấn đề liên quan đến biết cách không mang việc về nhà" },
      { id: "ngoc_p2", label: "Tự tin khi nói chuyện với sếp", description: "Vấn đề liên quan đến tự tin khi nói chuyện với sếp" },
      { id: "ngoc_p3", label: "Không sợ mắc sai lầm nữa", description: "Vấn đề liên quan đến không sợ mắc sai lầm nữa" },
      { id: "ngoc_p4", label: "Có người mentor dẫn đường", description: "Vấn đề liên quan đến có người mentor dẫn đường" },
      { id: "ngoc_p5", label: "Biết mình đang đi đúng hướng", description: "Vấn đề liên quan đến biết mình đang đi đúng hướng" },
      { id: "ngoc_p6", label: "Bớt cảm giác thua kém đồng nghiệp", description: "Vấn đề liên quan đến bớt cảm giác thua kém đồng nghiệp" },
      { id: "ngoc_p7", label: "Kiếm được nhiều tiền hơn", description: "Vấn đề liên quan đến kiếm được nhiều tiền hơn" },
      { id: "ngoc_p8", label: "Có ranh giới rõ giữa công việc và bản thân", description: "Vấn đề liên quan đến có ranh giới rõ giữa công việc và bản thân" },
      { id: "ngoc_p9", label: "Cảm thấy được công nhận trong team", description: "Vấn đề liên quan đến cảm thấy được công nhận trong team" },
    ],
    sets: [
      { set_id: "ngoc_s1", set_label: "Nhóm 1", items: ["ngoc_p1", "ngoc_p2", "ngoc_p3", "ngoc_p4"] },
      { set_id: "ngoc_s2", set_label: "Nhóm 2", items: ["ngoc_p2", "ngoc_p5", "ngoc_p6", "ngoc_p7"] },
      { set_id: "ngoc_s3", set_label: "Nhóm 3", items: ["ngoc_p3", "ngoc_p5", "ngoc_p8", "ngoc_p9"] },
      { set_id: "ngoc_s4", set_label: "Nhóm 4", items: ["ngoc_p1", "ngoc_p4", "ngoc_p6", "ngoc_p9"] },
      { set_id: "ngoc_s5", set_label: "Nhóm 5", items: ["ngoc_p2", "ngoc_p4", "ngoc_p8", "ngoc_p9"] },
      { set_id: "ngoc_s6", set_label: "Nhóm 6", items: ["ngoc_p1", "ngoc_p3", "ngoc_p6", "ngoc_p7"] },
      { set_id: "ngoc_s7", set_label: "Nhóm 7", items: ["ngoc_p4", "ngoc_p5", "ngoc_p7", "ngoc_p9"] },
      { set_id: "ngoc_s8", set_label: "Nhóm 8", items: ["ngoc_p1", "ngoc_p2", "ngoc_p5", "ngoc_p8"] },
      { set_id: "ngoc_s9", set_label: "Nhóm 9", items: ["ngoc_p3", "ngoc_p4", "ngoc_p7", "ngoc_p8"] }
    ],
    course_mapping: [
      { triggered_by: ["ngoc_p4","ngoc_p5","ngoc_p9"], problem_theme: "Định hướng sự nghiệp & phát triển bản thân", recommended_course: "Tư duy Linh hoạt — Career Edition", course_type: "online", cta: "Xem lộ trình ngay", urgency_message: "3 năm đầu đi làm định hình 80% sự nghiệp của bạn." },
      { triggered_by: ["ngoc_p1","ngoc_p2","ngoc_p3"], problem_theme: "EQ tại nơi làm việc", recommended_course: "Là Chính Mình — 21 ngày EQ", course_type: "online", cta: "Mở khóa ngay", urgency_message: "Kỹ năng mềm quyết định bạn có trụ lại và thăng tiến được không." },
      { triggered_by: ["ngoc_p6","ngoc_p7","ngoc_p8"], problem_theme: "Cân bằng tâm lý & tài chính", recommended_course: "EQ + Tài chính Cá nhân Bundle", course_type: "online", cta: "Xem bundle ưu đãi", urgency_message: "Tâm lý ổn định và tài chính rõ ràng — hai thứ cần song song." },
    ],
  },

  minh: {
    id: "minh",
    label: "Nhân viên văn phòng / Corporate",
    emoji: "🧭",
    color: "#378ADD",
    maxdiff_instruction: "Khi cạn kiệt năng lượng, điều gì giúp bạn PHỤC HỒI NHẤT và điều gì ÍT TÁC DỤNG NHẤT?",
    most_label: "PHỤC HỒI NHẤT",
    least_label: "ÍT TÁC DỤNG NHẤT",
    problem_pool: [
      { id: "minh_p1", label: "Có thời gian chỉ cho bản thân", description: "Vấn đề liên quan đến có thời gian chỉ cho bản thân" },
      { id: "minh_p2", label: "Cảm thấy công việc có ý nghĩa hơn", description: "Vấn đề liên quan đến cảm thấy công việc có ý nghĩa hơn" },
      { id: "minh_p3", label: "Ngủ ngon, không lo nghĩ ban đêm", description: "Vấn đề liên quan đến ngủ ngon, không lo nghĩ ban đêm" },
      { id: "minh_p4", label: "Bớt họp hành vô nghĩa", description: "Vấn đề liên quan đến bớt họp hành vô nghĩa" },
      { id: "minh_p5", label: "Được tăng lương / thưởng xứng đáng", description: "Vấn đề liên quan đến được tăng lương / thưởng xứng đáng" },
      { id: "minh_p6", label: "Có sếp thực sự lắng nghe", description: "Vấn đề liên quan đến có sếp thực sự lắng nghe" },
      { id: "minh_p7", label: "Tìm lại cảm giác hứng thú với công việc", description: "Vấn đề liên quan đến tìm lại cảm giác hứng thú với công việc" },
      { id: "minh_p8", label: "Biết khi nào cần nói không", description: "Vấn đề liên quan đến biết khi nào cần nói không" },
      { id: "minh_p9", label: "Có kế hoạch thoát khỏi vòng lặp này", description: "Vấn đề liên quan đến có kế hoạch thoát khỏi vòng lặp này" },
    ],
    sets: [
      { set_id: "minh_s1", set_label: "Nhóm 1", items: ["minh_p1", "minh_p2", "minh_p3", "minh_p4"] },
      { set_id: "minh_s2", set_label: "Nhóm 2", items: ["minh_p2", "minh_p5", "minh_p6", "minh_p7"] },
      { set_id: "minh_s3", set_label: "Nhóm 3", items: ["minh_p3", "minh_p5", "minh_p8", "minh_p9"] },
      { set_id: "minh_s4", set_label: "Nhóm 4", items: ["minh_p1", "minh_p4", "minh_p6", "minh_p9"] },
      { set_id: "minh_s5", set_label: "Nhóm 5", items: ["minh_p2", "minh_p4", "minh_p8", "minh_p9"] },
      { set_id: "minh_s6", set_label: "Nhóm 6", items: ["minh_p1", "minh_p3", "minh_p6", "minh_p7"] },
      { set_id: "minh_s7", set_label: "Nhóm 7", items: ["minh_p4", "minh_p5", "minh_p7", "minh_p9"] },
      { set_id: "minh_s8", set_label: "Nhóm 8", items: ["minh_p1", "minh_p2", "minh_p5", "minh_p8"] },
      { set_id: "minh_s9", set_label: "Nhóm 9", items: ["minh_p3", "minh_p4", "minh_p7", "minh_p8"] }
    ],
    course_mapping: [
      { triggered_by: ["minh_p1","minh_p2","minh_p7"], problem_theme: "Ý nghĩa sống & tự nhận thức", recommended_course: "Là Chính Mình — 21 ngày EQ", course_type: "online", cta: "Bắt đầu hành trình", urgency_message: "Bắt đầu từ bên trong — mọi thứ bên ngoài sẽ theo sau." },
      { triggered_by: ["minh_p4","minh_p5","minh_p6"], problem_theme: "Leadership & EQ nghề nghiệp", recommended_course: "Tư Duy Linh Hoạt & Nội Lực Tâm Lý", course_type: "online", cta: "Xem chương trình", urgency_message: "EQ là kỹ năng phân biệt người bình thường và người xuất sắc tại công sở." },
      { triggered_by: ["minh_p3","minh_p8","minh_p9"], problem_theme: "Phục hồi & chuyển hướng", recommended_course: "Retreat Cuối Tuần — Tái Thiết Kế", course_type: "retreat", cta: "Xem lịch gần nhất", urgency_message: "Đôi khi bạn cần ra khỏi màn hình để thấy rõ cuộc sống của mình." },
    ],
  },

  ha: {
    id: "ha",
    label: "Freelancer / Tự kinh doanh",
    emoji: "🦋",
    color: "#D85A30",
    maxdiff_instruction: "Trong công việc, điều nào bạn COI TRỌNG NHẤT — và điều nào bạn ÍT BẬN TÂM NHẤT?",
    most_label: "COI TRỌNG NHẤT",
    least_label: "ÍT BẬN TÂM NHẤT",
    problem_pool: [
      { id: "ha_p1", label: "Thu nhập ổn định hơn", description: "Vấn đề liên quan đến thu nhập ổn định hơn" },
      { id: "ha_p2", label: "Không còn làm việc một mình nữa", description: "Vấn đề liên quan đến không còn làm việc một mình nữa" },
      { id: "ha_p3", label: "Biết cách định giá bản thân", description: "Vấn đề liên quan đến biết cách định giá bản thân" },
      { id: "ha_p4", label: "Có khách hàng chất lượng hơn", description: "Vấn đề liên quan đến có khách hàng chất lượng hơn" },
      { id: "ha_p5", label: "Quản lý thời gian tốt hơn", description: "Vấn đề liên quan đến quản lý thời gian tốt hơn" },
      { id: "ha_p6", label: "Xây được thương hiệu cá nhân", description: "Vấn đề liên quan đến xây được thương hiệu cá nhân" },
      { id: "ha_p7", label: "Bớt cảm giác bấp bênh về tài chính", description: "Vấn đề liên quan đến bớt cảm giác bấp bênh về tài chính" },
      { id: "ha_p8", label: "Tìm lại năng lượng làm việc", description: "Vấn đề liên quan đến tìm lại năng lượng làm việc" },
      { id: "ha_p9", label: "Có hệ thống để không phụ thuộc vào mình 100%", description: "Vấn đề liên quan đến có hệ thống để không phụ thuộc vào mình 100%" },
    ],
    sets: [
      { set_id: "ha_s1", set_label: "Nhóm 1", items: ["ha_p1", "ha_p2", "ha_p3", "ha_p4"] },
      { set_id: "ha_s2", set_label: "Nhóm 2", items: ["ha_p2", "ha_p5", "ha_p6", "ha_p7"] },
      { set_id: "ha_s3", set_label: "Nhóm 3", items: ["ha_p3", "ha_p5", "ha_p8", "ha_p9"] },
      { set_id: "ha_s4", set_label: "Nhóm 4", items: ["ha_p1", "ha_p4", "ha_p6", "ha_p9"] },
      { set_id: "ha_s5", set_label: "Nhóm 5", items: ["ha_p2", "ha_p4", "ha_p8", "ha_p9"] },
      { set_id: "ha_s6", set_label: "Nhóm 6", items: ["ha_p1", "ha_p3", "ha_p6", "ha_p7"] },
      { set_id: "ha_s7", set_label: "Nhóm 7", items: ["ha_p4", "ha_p5", "ha_p7", "ha_p9"] },
      { set_id: "ha_s8", set_label: "Nhóm 8", items: ["ha_p1", "ha_p2", "ha_p5", "ha_p8"] },
      { set_id: "ha_s9", set_label: "Nhóm 9", items: ["ha_p3", "ha_p4", "ha_p7", "ha_p8"] }
    ],
    course_mapping: [
      { triggered_by: ["ha_p1","ha_p3","ha_p7"], problem_theme: "Tâm lý tài chính & EQ kinh doanh", recommended_course: "EQ cho Người Tự Kinh Doanh", course_type: "online", cta: "Khám phá chương trình", urgency_message: "Cảm xúc và tiền bạc của người freelance gắn liền nhau hơn bạn nghĩ." },
      { triggered_by: ["ha_p2","ha_p4","ha_p6"], problem_theme: "Kết nối cộng đồng & phát triển", recommended_course: "Mastermind Freelancer Nedu", course_type: "community", cta: "Tham gia cộng đồng", urgency_message: "Một cộng đồng đúng người có thể thay đổi cả trajectory của bạn." },
      { triggered_by: ["ha_p5","ha_p8","ha_p9"], problem_theme: "Hệ thống & ranh giới cá nhân", recommended_course: "Là Chính Mình — Module Năng Lượng & Ranh Giới", course_type: "online", cta: "Xem module", urgency_message: "Ranh giới lành mạnh không phải ích kỷ — đó là nền tảng để làm việc bền vững." },
    ],
  },

  khanh: {
    id: "khanh",
    label: "Digital Nomad / Creator / YouTuber",
    emoji: "🧳",
    color: "#0F6E56",
    maxdiff_instruction: 'Để thực sự "Là Chính Mình", điều gì là NỀN MÓNG NHẤT và điều gì bạn CÓ THỂ BỎ QUA?',
    most_label: "NỀN MÓNG NHẤT",
    least_label: "CÓ THỂ BỎ QUA",
    problem_pool: [
      { id: "khanh_p1", label: "Biết rõ mình là ai — không cần ai xác nhận", description: "Vấn đề liên quan đến biết rõ mình là ai — không cần ai xác nhận" },
      { id: "khanh_p2", label: "Tạo ra nội dung thật sự ý nghĩa", description: "Vấn đề liên quan đến tạo ra nội dung thật sự ý nghĩa" },
      { id: "khanh_p3", label: "Không bị ý kiến người khác chi phối", description: "Vấn đề liên quan đến không bị ý kiến người khác chi phối" },
      { id: "khanh_p4", label: "Có thu nhập từ đúng thứ mình thích", description: "Vấn đề liên quan đến có thu nhập từ đúng thứ mình thích" },
      { id: "khanh_p5", label: "Được tự do chọn nơi sống và làm việc", description: "Vấn đề liên quan đến được tự do chọn nơi sống và làm việc" },
      { id: "khanh_p6", label: "Xây được cộng đồng thực sự kết nối", description: "Vấn đề liên quan đến xây được cộng đồng thực sự kết nối" },
      { id: "khanh_p7", label: "Không còn burnout vì content", description: "Vấn đề liên quan đến không còn burnout vì content" },
      { id: "khanh_p8", label: "Biết cách cân bằng công khai và đời tư", description: "Vấn đề liên quan đến biết cách cân bằng công khai và đời tư" },
      { id: "khanh_p9", label: "Tìm lại lý do ban đầu mình bắt đầu", description: "Vấn đề liên quan đến tìm lại lý do ban đầu mình bắt đầu" },
    ],
    sets: [
      { set_id: "khanh_s1", set_label: "Nhóm 1", items: ["khanh_p1", "khanh_p2", "khanh_p3", "khanh_p4"] },
      { set_id: "khanh_s2", set_label: "Nhóm 2", items: ["khanh_p2", "khanh_p5", "khanh_p6", "khanh_p7"] },
      { set_id: "khanh_s3", set_label: "Nhóm 3", items: ["khanh_p3", "khanh_p5", "khanh_p8", "khanh_p9"] },
      { set_id: "khanh_s4", set_label: "Nhóm 4", items: ["khanh_p1", "khanh_p4", "khanh_p6", "khanh_p9"] },
      { set_id: "khanh_s5", set_label: "Nhóm 5", items: ["khanh_p2", "khanh_p4", "khanh_p8", "khanh_p9"] },
      { set_id: "khanh_s6", set_label: "Nhóm 6", items: ["khanh_p1", "khanh_p3", "khanh_p6", "khanh_p7"] },
      { set_id: "khanh_s7", set_label: "Nhóm 7", items: ["khanh_p4", "khanh_p5", "khanh_p7", "khanh_p9"] },
      { set_id: "khanh_s8", set_label: "Nhóm 8", items: ["khanh_p1", "khanh_p2", "khanh_p5", "khanh_p8"] },
      { set_id: "khanh_s9", set_label: "Nhóm 9", items: ["khanh_p3", "khanh_p4", "khanh_p7", "khanh_p8"] }
    ],
    course_mapping: [
      { triggered_by: ["khanh_p1","khanh_p7","khanh_p8"], problem_theme: "Nervous system regulation & inner stillness", recommended_course: "Là Chính Mình — Signature Program", course_type: "signature", cta: "Xem chương trình đầy đủ →", urgency_message: "Khi nervous system được regulate, creativity và clarity tự nhiên xuất hiện." },
      { triggered_by: ["khanh_p2","khanh_p3","khanh_p9"], problem_theme: "EQ cho Creator & identity work", recommended_course: "1-on-1 Deep Dive — 4 buổi", course_type: "coaching", cta: "Đặt lịch khám phá →", urgency_message: "Một vài buổi coaching đúng thời điểm có thể unlock những gì bạn đang block." },
      { triggered_by: ["khanh_p4","khanh_p5","khanh_p6"], problem_theme: "Attachment & kết nối sâu", recommended_course: "Digital Nomad Retreat — Chiang Mai", course_type: "retreat", cta: "Xem lịch gần nhất →", urgency_message: "Đôi khi bạn cần một cộng đồng thật sự để nhớ rằng mình không đi một mình." },
    ],
  },

  linh: {
    id: "linh",
    label: "Quản lý / Chủ doanh nghiệp nhỏ",
    emoji: "💼",
    color: "#534AB7",
    maxdiff_instruction: "Ở vị trí hiện tại, mục tiêu nào với bạn là CẤP THIẾT NHẤT và cái nào CHƯA CẦN ĐẾN?",
    most_label: "CẤP THIẾT NHẤT",
    least_label: "CHƯA CẦN ĐẾN",
    problem_pool: [
      { id: "linh_p1", label: "Team tự chạy không cần sếp kè kè", description: "Vấn đề liên quan đến team tự chạy không cần sếp kè kè" },
      { id: "linh_p2", label: "Doanh thu tăng trưởng đều đặn", description: "Vấn đề liên quan đến doanh thu tăng trưởng đều đặn" },
      { id: "linh_p3", label: "Không còn ôm hết việc một mình", description: "Vấn đề liên quan đến không còn ôm hết việc một mình" },
      { id: "linh_p4", label: "Biết cách giữ chân người giỏi", description: "Vấn đề liên quan đến biết cách giữ chân người giỏi" },
      { id: "linh_p5", label: "Có hệ thống rõ ràng từ A đến Z", description: "Vấn đề liên quan đến có hệ thống rõ ràng từ a đến z" },
      { id: "linh_p6", label: "Bản thân không bị burnout", description: "Vấn đề liên quan đến bản thân không bị burnout" },
      { id: "linh_p7", label: "Ra quyết định nhanh và đúng hơn", description: "Vấn đề liên quan đến ra quyết định nhanh và đúng hơn" },
      { id: "linh_p8", label: "Xây được văn hóa team thật sự", description: "Vấn đề liên quan đến xây được văn hóa team thật sự" },
      { id: "linh_p9", label: "Có thời gian nghĩ chiến lược thay vì chữa cháy", description: "Vấn đề liên quan đến có thời gian nghĩ chiến lược thay vì chữa cháy" },
    ],
    sets: [
      { set_id: "linh_s1", set_label: "Nhóm 1", items: ["linh_p1", "linh_p2", "linh_p3", "linh_p4"] },
      { set_id: "linh_s2", set_label: "Nhóm 2", items: ["linh_p2", "linh_p5", "linh_p6", "linh_p7"] },
      { set_id: "linh_s3", set_label: "Nhóm 3", items: ["linh_p3", "linh_p5", "linh_p8", "linh_p9"] },
      { set_id: "linh_s4", set_label: "Nhóm 4", items: ["linh_p1", "linh_p4", "linh_p6", "linh_p9"] },
      { set_id: "linh_s5", set_label: "Nhóm 5", items: ["linh_p2", "linh_p4", "linh_p8", "linh_p9"] },
      { set_id: "linh_s6", set_label: "Nhóm 6", items: ["linh_p1", "linh_p3", "linh_p6", "linh_p7"] },
      { set_id: "linh_s7", set_label: "Nhóm 7", items: ["linh_p4", "linh_p5", "linh_p7", "linh_p9"] },
      { set_id: "linh_s8", set_label: "Nhóm 8", items: ["linh_p1", "linh_p2", "linh_p5", "linh_p8"] },
      { set_id: "linh_s9", set_label: "Nhóm 9", items: ["linh_p3", "linh_p4", "linh_p7", "linh_p8"] }
    ],
    course_mapping: [
      { triggered_by: ["linh_p1","linh_p6","linh_p9"], problem_theme: "Phục hồi sâu & tái kết nối bản thân", recommended_course: "Retreat Chữa Lành 9 Ngày — Đà Lạt", course_type: "retreat", cta: "Đặt chỗ ngay", urgency_message: "9 ngày đầu tư cho bản thân để trở lại mạnh mẽ hơn trong 9 tháng tiếp theo." },
      { triggered_by: ["linh_p2","linh_p3","linh_p4","linh_p5","linh_p7","linh_p8"], problem_theme: "EQ lãnh đạo & ra quyết định", recommended_course: "Là Chính Mình — Leadership Edition", course_type: "online", cta: "Mở khóa bài học", urgency_message: "Leader hiểu bản thân thì mới lãnh đạo người khác hiệu quả được." },
    ],
  },

  van: {
    id: "van",
    label: "Phụ nữ / Mẹ cân bằng gia đình & sự nghiệp",
    emoji: "🌸",
    color: "#D4537E",
    maxdiff_instruction: 'Để có cuộc sống trọn vẹn cả vật chất lẫn tinh thần, đâu là "chìa khóa" NHẤT với bạn?',
    most_label: "CHÌA KHÓA NHẤT",
    least_label: "KÉM QUAN TRỌNG HƠN",
    problem_pool: [
      { id: "van_p1", label: "Không còn cảm giác tội lỗi khi chọn bản thân", description: "Vấn đề liên quan đến không còn cảm giác tội lỗi khi chọn bản thân" },
      { id: "van_p2", label: "Có thời gian riêng — dù chỉ 30 phút/ngày", description: "Vấn đề liên quan đến có thời gian riêng — dù chỉ 30 phút/ngày" },
      { id: "van_p3", label: "Được công nhận ở cả nhà lẫn công việc", description: "Vấn đề liên quan đến được công nhận ở cả nhà lẫn công việc" },
      { id: "van_p4", label: "Con cái ổn định — mình mới ổn được", description: "Vấn đề liên quan đến con cái ổn định — mình mới ổn được" },
      { id: "van_p5", label: "Tài chính do mình kiểm soát", description: "Vấn đề liên quan đến tài chính do mình kiểm soát" },
      { id: "van_p6", label: "Không còn cảm giác cô đơn trong hành trình này", description: "Vấn đề liên quan đến không còn cảm giác cô đơn trong hành trình này" },
      { id: "van_p7", label: "Biết cách đặt ranh giới mà không bị ghét", description: "Vấn đề liên quan đến biết cách đặt ranh giới mà không bị ghét" },
      { id: "van_p8", label: "Tìm lại phiên bản mình trước khi lấy chồng / có con", description: "Vấn đề liên quan đến tìm lại phiên bản mình trước khi lấy chồng / có con" },
      { id: "van_p9", label: "Có người đồng hành thực sự hiểu mình", description: "Vấn đề liên quan đến có người đồng hành thực sự hiểu mình" },
    ],
    sets: [
      { set_id: "van_s1", set_label: "Nhóm 1", items: ["van_p1", "van_p2", "van_p3", "van_p4"] },
      { set_id: "van_s2", set_label: "Nhóm 2", items: ["van_p2", "van_p5", "van_p6", "van_p7"] },
      { set_id: "van_s3", set_label: "Nhóm 3", items: ["van_p3", "van_p5", "van_p8", "van_p9"] },
      { set_id: "van_s4", set_label: "Nhóm 4", items: ["van_p1", "van_p4", "van_p6", "van_p9"] },
      { set_id: "van_s5", set_label: "Nhóm 5", items: ["van_p2", "van_p4", "van_p8", "van_p9"] },
      { set_id: "van_s6", set_label: "Nhóm 6", items: ["van_p1", "van_p3", "van_p6", "van_p7"] },
      { set_id: "van_s7", set_label: "Nhóm 7", items: ["van_p4", "van_p5", "van_p7", "van_p9"] },
      { set_id: "van_s8", set_label: "Nhóm 8", items: ["van_p1", "van_p2", "van_p5", "van_p8"] },
      { set_id: "van_s9", set_label: "Nhóm 9", items: ["van_p3", "van_p4", "van_p7", "van_p8"] }
    ],
    course_mapping: [
      { triggered_by: ["van_p1","van_p2","van_p5","van_p7"], problem_theme: "Ranh giới & tái tạo năng lượng", recommended_course: "Cân bằng Nội Tâm cho Mẹ", course_type: "online", cta: "Bắt đầu hôm nay", urgency_message: "Bạn không thể rót từ một chiếc cốc rỗng. Đây là cách nạp lại." },
      { triggered_by: ["van_p3","van_p4","van_p6","van_p8","van_p9"], problem_theme: "Tự nhận thức & bản sắc cá nhân", recommended_course: "Weekend Retreat cho Phụ Nữ", course_type: "retreat", cta: "Xem lịch gần nhất", urgency_message: "2 ngày không có ai cần bạn — chỉ có bạn và chính mình." },
    ],
  },

  thao: {
    id: "thao",
    label: "Giáo viên / Công chức / Viên chức",
    emoji: "🌾",
    color: "#BA7517",
    maxdiff_instruction: "Lắng nghe trực giác ngay lúc này: điều gì đang KÊU GỌI BẠN NHẤT và điều gì MỜ NHẠT NHẤT?",
    most_label: "KÊU GỌI NHẤT",
    least_label: "MỜ NHẠT NHẤT",
    problem_pool: [
      { id: "thao_p1", label: "Tìm lại lý do mình chọn nghề này", description: "Vấn đề liên quan đến tìm lại lý do mình chọn nghề này" },
      { id: "thao_p2", label: "Không còn cảm giác bị mắc kẹt", description: "Vấn đề liên quan đến không còn cảm giác bị mắc kẹt" },
      { id: "thao_p3", label: "Được lắng nghe — không chỉ làm theo lệnh", description: "Vấn đề liên quan đến được lắng nghe — không chỉ làm theo lệnh" },
      { id: "thao_p4", label: "Có thu nhập thêm ngoài lương", description: "Vấn đề liên quan đến có thu nhập thêm ngoài lương" },
      { id: "thao_p5", label: "Sống đúng với giá trị của mình hơn", description: "Vấn đề liên quan đến sống đúng với giá trị của mình hơn" },
      { id: "thao_p6", label: "Bớt mệt mỏi vì áp lực hành chính", description: "Vấn đề liên quan đến bớt mệt mỏi vì áp lực hành chính" },
      { id: "thao_p7", label: "Được phát triển chứ không chỉ duy trì", description: "Vấn đề liên quan đến được phát triển chứ không chỉ duy trì" },
      { id: "thao_p8", label: "Có không gian sáng tạo trong công việc", description: "Vấn đề liên quan đến có không gian sáng tạo trong công việc" },
      { id: "thao_p9", label: "Biết bước tiếp theo của mình là gì", description: "Vấn đề liên quan đến biết bước tiếp theo của mình là gì" },
    ],
    sets: [
      { set_id: "thao_s1", set_label: "Nhóm 1", items: ["thao_p1", "thao_p2", "thao_p3", "thao_p4"] },
      { set_id: "thao_s2", set_label: "Nhóm 2", items: ["thao_p2", "thao_p5", "thao_p6", "thao_p7"] },
      { set_id: "thao_s3", set_label: "Nhóm 3", items: ["thao_p3", "thao_p5", "thao_p8", "thao_p9"] },
      { set_id: "thao_s4", set_label: "Nhóm 4", items: ["thao_p1", "thao_p4", "thao_p6", "thao_p9"] },
      { set_id: "thao_s5", set_label: "Nhóm 5", items: ["thao_p2", "thao_p4", "thao_p8", "thao_p9"] },
      { set_id: "thao_s6", set_label: "Nhóm 6", items: ["thao_p1", "thao_p3", "thao_p6", "thao_p7"] },
      { set_id: "thao_s7", set_label: "Nhóm 7", items: ["thao_p4", "thao_p5", "thao_p7", "thao_p9"] },
      { set_id: "thao_s8", set_label: "Nhóm 8", items: ["thao_p1", "thao_p2", "thao_p5", "thao_p8"] },
      { set_id: "thao_s9", set_label: "Nhóm 9", items: ["thao_p3", "thao_p4", "thao_p7", "thao_p8"] }
    ],
    course_mapping: [
      { triggered_by: ["thao_p1","thao_p2","thao_p5"], problem_theme: "Tự nhận thức & can đảm thay đổi", recommended_course: "Bắt Đầu Từ Bên Trong", course_type: "online", cta: "Xem chương trình", urgency_message: "Hiểu mình trước — can đảm sẽ đến sau." },
      { triggered_by: ["thao_p6","thao_p7","thao_p8","thao_p9"], problem_theme: "Ý nghĩa công việc & EQ", recommended_course: "Là Chính Mình — 21 ngày EQ", course_type: "online", cta: "Bắt đầu hành trình", urgency_message: "Thay đổi bắt đầu từ cách bạn nhìn mình — không phải từ hoàn cảnh bên ngoài." },
      { triggered_by: ["thao_p3","thao_p4"], problem_theme: "Cộng đồng & phát triển tài chính", recommended_course: "Cộng đồng Nedu Tỉnh Thành", course_type: "community", cta: "Tham gia miễn phí", urgency_message: "Người xung quanh ảnh hưởng đến bạn nhiều hơn bạn nghĩ — hãy chọn đúng cộng đồng." },
    ],
  },

  lan: {
    id: "lan",
    label: "Lãnh đạo cấp cao / Doanh nhân",
    emoji: "🏔️",
    color: "#5F5E5A",
    maxdiff_instruction: "Nếu thiết kế lại lộ trình từ hôm nay, bạn chọn gì làm KIM CHỈ NAM NHẤT và BỎ GÌ LẠI SAU CÙNG?",
    most_label: "KIM CHỈ NAM NHẤT",
    least_label: "BỎ LẠI SAU CÙNG",
    problem_pool: [
      { id: "lan_p1", label: "Tìm lại ý nghĩa đằng sau tất cả những gì đang làm", description: "Vấn đề liên quan đến tìm lại ý nghĩa đằng sau tất cả những gì đang làm" },
      { id: "lan_p2", label: "Sức khỏe — nền tảng của mọi thứ còn lại", description: "Vấn đề liên quan đến sức khỏe — nền tảng của mọi thứ còn lại" },
      { id: "lan_p3", label: "Xây dựng di sản — thứ còn mãi sau khi mình rời đi", description: "Vấn đề liên quan đến xây dựng di sản — thứ còn mãi sau khi mình rời đi" },
      { id: "lan_p4", label: "Có người kế thừa đáng tin cậy", description: "Vấn đề liên quan đến có người kế thừa đáng tin cậy" },
      { id: "lan_p5", label: "Bớt kiểm soát — tin tưởng hơn vào team", description: "Vấn đề liên quan đến bớt kiểm soát — tin tưởng hơn vào team" },
      { id: "lan_p6", label: "Tìm lại sự cân bằng đã đánh đổi bao năm", description: "Vấn đề liên quan đến tìm lại sự cân bằng đã đánh đổi bao năm" },
      { id: "lan_p7", label: "Kết nối với những người cùng tầm nhìn", description: "Vấn đề liên quan đến kết nối với những người cùng tầm nhìn" },
      { id: "lan_p8", label: "Dành thời gian cho gia đình trước khi quá muộn", description: "Vấn đề liên quan đến dành thời gian cho gia đình trước khi quá muộn" },
      { id: "lan_p9", label: "Biết khi nào cần buông tay và bắt đầu cái mới", description: "Vấn đề liên quan đến biết khi nào cần buông tay và bắt đầu cái mới" },
    ],
    sets: [
      { set_id: "lan_s1", set_label: "Nhóm 1", items: ["lan_p1", "lan_p2", "lan_p3", "lan_p4"] },
      { set_id: "lan_s2", set_label: "Nhóm 2", items: ["lan_p2", "lan_p5", "lan_p6", "lan_p7"] },
      { set_id: "lan_s3", set_label: "Nhóm 3", items: ["lan_p3", "lan_p5", "lan_p8", "lan_p9"] },
      { set_id: "lan_s4", set_label: "Nhóm 4", items: ["lan_p1", "lan_p4", "lan_p6", "lan_p9"] },
      { set_id: "lan_s5", set_label: "Nhóm 5", items: ["lan_p2", "lan_p4", "lan_p8", "lan_p9"] },
      { set_id: "lan_s6", set_label: "Nhóm 6", items: ["lan_p1", "lan_p3", "lan_p6", "lan_p7"] },
      { set_id: "lan_s7", set_label: "Nhóm 7", items: ["lan_p4", "lan_p5", "lan_p7", "lan_p9"] },
      { set_id: "lan_s8", set_label: "Nhóm 8", items: ["lan_p1", "lan_p2", "lan_p5", "lan_p8"] },
      { set_id: "lan_s9", set_label: "Nhóm 9", items: ["lan_p3", "lan_p4", "lan_p7", "lan_p8"] }
    ],
    course_mapping: [
      { triggered_by: ["lan_p1","lan_p2","lan_p3"], problem_theme: "Ý nghĩa sống & tái thiết kế", recommended_course: "VIP Retreat 7 Ngày — Chuyển Hóa", course_type: "retreat", cta: "Đăng ký tư vấn riêng", urgency_message: "Ở một điểm nhất định, bạn không cần thêm kiến thức — bạn cần không gian để thấy rõ." },
      { triggered_by: ["lan_p4","lan_p5","lan_p6","lan_p7","lan_p8","lan_p9"], problem_theme: "Kết nối, buông bỏ & phục hồi sâu", recommended_course: "1-on-1 Executive Coaching — 12 buổi", course_type: "coaching", cta: "Xếp lịch khám phá", urgency_message: "Coaching không phải để fix bạn — mà để unlock những gì bạn đã biết nhưng chưa thấy." },
    ],
  },

};
