/**
 * Cloudflare Worker entrypoint — wraps OpenNext-generated worker.
 *
 * Adds a `scheduled()` handler so Cloudflare Cron Triggers
 * (declared in wrangler.jsonc → triggers.crons) can drive the
 * daily email-sequence (drip mode).
 *
 * Generated worker `.open-next/worker.js` (created by
 * `opennextjs-cloudflare build`) exports:
 *   - default { fetch }
 *   - named: DOQueueHandler, DOShardedTagCache, BucketCachePurge
 *     (re-exported below — wrangler binds them by class name)
 */

// @ts-expect-error — file is generated by `opennextjs-cloudflare build`
import openNextHandler from '../.open-next/worker.js';

// @ts-expect-error — Durable Object classes referenced by wrangler bindings
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from '../.open-next/worker.js';

interface Env {
  NEXT_PUBLIC_REPORT_BASE_URL?: string;
  CRON_SECRET?: string;
}

// Cloudflare runtime types (ExecutionContext, ScheduledController) chỉ có khi
// cài @cloudflare/workers-types. Để tránh thêm dep, dùng `any` ở đây — file
// này chạy trong workerd runtime nên các param đã được Cloudflare đảm bảo type.
type CFContext = { waitUntil: (promise: Promise<unknown>) => void };

export default {
  fetch: (req: Request, env: Env, ctx: CFContext) =>
    openNextHandler.fetch(req, env, ctx),

  async scheduled(_event: unknown, env: Env, ctx: CFContext) {
    const baseUrl = env.NEXT_PUBLIC_REPORT_BASE_URL;
    const cronSecret = env.CRON_SECRET;

    if (!baseUrl || !cronSecret) {
      console.error('[cron] Missing NEXT_PUBLIC_REPORT_BASE_URL or CRON_SECRET');
      return;
    }

    ctx.waitUntil(
      (async () => {
        try {
          const res = await fetch(`${baseUrl}/api/cron/email-sequence`, {
            headers: { Authorization: `Bearer ${cronSecret}` },
          });
          const body = await res.text();
          if (!res.ok) {
            console.error('[cron] email-sequence failed', res.status, body);
          } else {
            console.log('[cron] email-sequence ok', body);
          }
        } catch (err) {
          console.error('[cron] email-sequence error', err);
        }
      })()
    );
  },
};
